import type { Metadata } from "next";
import { Geist, Geist_Mono, Darker_Grotesque } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/organisms/Navigation";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const font = Darker_Grotesque();
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${font.className}  antialiased`}>
                <Navigation user={false} />
                <main>{children}</main>
            </body>
        </html>
    );
}
